swagger: "2.0"
info:
  version: "0.0.1"
  title: searchkit-apis
# during dev, should point to your local machine
host: localhost:5000
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /specs/_search:
    # binds a127 app logic to a route
    x-swagger-router-controller: specs
    post:
      description: Search 'API' specs against ElasticSearch.
      # used as the method name of the controller
      operationId: searchApiSpecs
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/SearchRequest"
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Forbidden
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  SearchRequest:
    type: object
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
