swagger: '2.0'
info:
  version: 0.0.1
  title: searchkit-apis
host: 'localhost:5000'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /specs/_search:
    x-swagger-router-controller: specs
    post:
      description: Search 'API' specs against ElasticSearch.
      operationId: searchApiSpecs
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/SearchRequest'
      responses:
        '200':
          description: Success
        default:
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  SearchRequest:
    type: object
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
